name: TechCrunch Web Scrape Pipeline

on:
  schedule:
    - cron: "0 6 * * *"  # Every day at 6am UTC
  workflow_dispatch:      # Manual trigger option

jobs:
  scrape-and-store:
    runs-on: ubuntu-latest

    env:
      FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Run web scraper
        run: python notebooks/Techcrunch_Web_Scrape_Extract_Load_Raw.py
